default_values:
  platform_name: wilkes
  platform_version: 4.4.0
  bug_fixes: N/A
update_repository:
  enabled: true
  location: ~/Documents/Updates
resource_files:
  mandatory:
  - update-descriptor.yaml
  - LICENSE.txt
  optional:
  - NOT_A_CONTRIBUTION.txt
  - instructions.txt
  skip:
  - README.txt
platform_versions:
  4.4.0: wilkes
