process_readme: true
auto_validate: true
default_values:
  platform_name: wilkes
  platform_version: 4.4.0
  bug_fixes: N/A
check_md5: false
update_repository: $HOME/Documents/Updates
resource_files:
  mandatory:
  - update-descriptor.yaml
  - LICENSE.txt
  optional:
  - NOT_A_CONTRIBUTION.txt
  - instructions.txt
  skip:
  - README.txt
